@host=localhost:80

### Login
POST http://{{host}}/login
Content-Type: application/json

{
  "id": "EnterShow9372",
  "password": "password"
}














### Register
POST http://{{host}}/register
Content-Type: application/json

{
  "first_name": "John",
  "second_name": "Doe",
  "birthdate": "1990-01-01",
  "biography": "Software developer with a passion for open-source projects.",
  "city": "New York",
  "password": "password"
}