@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbnRlclNob3c5MzcyIiwiZ2l2ZW5fbmFtZSI6IldpbGxpYW0iLCJmYW1pbHlfbmFtZSI6IldhdHNvbiIsImp0aSI6IjNhOGFmNGM2LTNkOTAtNDE5OS04ZGEzLTcxYTM2N2E0MmVkOCIsImV4cCI6MTcyNjA5Mzk4MiwiaXNzIjoiSGlnaGxvYWRTb2NpYWwiLCJhdWQiOiJIaWdobG9hZFNvY2lhbCJ9.u6cu-d8eyWinO8mLjaFsRwXfCYOzSUJTCpSRLHl3kBk
GET http://localhost:80/friend/list
Content-Type: application/json
Authorization: Bearer {{token}}


### Delete request
PUT http://localhost:8080/api/friend/delete/BabySister1111
Content-Type: application/json
Authorization: Bearer {{token}}