@host=localhost:80

### Get by id
GET http://{{host}}/user/get/EnterShow9372
Content-Type: application/json

### Search
GET http://{{host}}/user/search?first_name=W&second_name=W
Content-Type: application/json
